@baseurl = https://8080-thiagobdag-springwikiap-d7karjvwtxc.ws-us114.gitpod.io

###
GET {{baseurl}}/obras

###
POST {{baseurl}}/obras
Content-Type: application/json

{
    "titulo":"Better Call Saul",
    "autor":"Vince Gilligan",
    "genero":"Ação/Terror",
    "duracao":"6 Temporadas",
    "categoria": {"id": 1}
}
###
PUT {{baseurl}}/obras/4
Content-Type: application/json

{
    "titulo":"Better Call Saul",
    "autor":"Vince Gilligan",
    "genero":"Crime/Drama/Humor Ácido",
    "duracao":"6 Temporadas",
    "categoria": {"id": 1}
}
###

DELETE https://8080-thiagobdag-springwikiap-d7karjvwtxc.ws-us114.gitpod.io/obras/3

###