@baseurl = https://8080-thiagobdag-springwikiap-d7karjvwtxc.ws-us114.gitpod.io

###
GET {{baseurl}}/personagens

###
POST {{baseurl}}/personagens
Content-Type: application/json

{
    "imagem": "https://i.imgur.com/TKStDdc.png",
    "nome":"Hetttsss",
    "idade": 52,
    "sexo": "Homem Velho"
}

###
PUT {{baseurl}}/personagens/1
Content-Type: application/json

{
    "imagem": "https://i.imgur.com/TKStDdc.png",
    "nome":"Heisenberg",
    "idade": 52,
    "sexo": "Homem"
}

###
DELETE {{baseurl}}/personagens/2